# Site settings
title: Help Me Out
email: vinicius.m.do.carmo@gmail.com
author: "Vinícius do Carmo"
description: "Blog que tem como enfoque ajudar os alunos de computação da <a href='http://ufc.br'>UFC</a> e aos estudantes de computação em geral."
url: "http://help-me-out.herokuapp.com"
twitter_username: vinimdocarmo
github_username:  vinimdocarmo

# Build settings
markdown: kramdown
permalink: /post/:title
exclude: [Gemfile, Gemfile.lock, Procfile, vendor, gems]
